import { expect, test } from '@playwright/test'

for (const fixture of ['layout.html', 'instagram-layout.html']) {
  test(`synthetic layout fixture: ${fixture}`, async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto(`/tests/${fixture}`)
    const results = page.locator('#results')
    await expect(results).toContainText('PASS')
    const lines = (await results.innerText()).trim().split('\n')
    expect(lines.length).toBeGreaterThan(0)
    expect(lines.filter(line => !line.startsWith('PASS '))).toEqual([])
    expect(errors).toEqual([])
  })
}

test('home DOM remains hidden through navigation while search/channel DOM stays visible', async ({ page }) => {
  await page.goto('/tests/browser/runtime.html')
  await expect(page.locator('#home-grid')).toBeHidden()
  await expect(page.locator('#channel-grid')).toBeVisible()
  await expect(page.locator('ytd-search #contents')).toBeVisible()
  await page.getByRole('button', { name: 'Navigate to results' }).click()
  await expect(page.locator('#navigations')).toHaveText('1')
  await expect(page).toHaveURL(/\/results\?search_query=example$/)
  await expect(page.locator('#home-grid')).toBeHidden()
  await expect(page.locator('ytd-search #contents')).toBeVisible()
  await page.getByRole('button', { name: 'Disable Home hiding' }).click()
  await expect(page.locator('#home-grid')).toBeVisible()
  await expect(page.locator('#navigations')).toHaveText('1')
})

test('native ResizeObserver notices content growth inside a fixed viewport and stops after cleanup', async ({ page }) => {
  await page.goto('/tests/browser/runtime.html')
  await expect(page.locator('#overflow')).toHaveText('false')
  await page.getByRole('button', { name: 'Expand content' }).click()
  await expect(page.locator('#settled')).toHaveText('300')
  await expect(page.locator('#overflow')).toHaveText('true')
  await page.getByRole('button', { name: 'Shrink content' }).click()
  await expect(page.locator('#settled')).toHaveText('40')
  await expect(page.locator('#overflow')).toHaveText('false')
  await page.getByRole('button', { name: 'Disconnect resize observer' }).click()
  await page.getByRole('button', { name: 'Expand content' }).click()
  await expect(page.locator('#settled')).toHaveText('300')
  expect(await page.locator('#viewport').evaluate(el => el.scrollHeight > el.clientHeight)).toBe(true)
  await expect(page.locator('#overflow')).toHaveText('false')
})

test('floating-only hiding preserves DM navigation, handles new launchers, and restores on master off', async ({ page }) => {
  await page.goto('/tests/browser/floating-dms.html')
  await expect(page.locator('#launcher')).toBeVisible()
  await page.locator('#child').click()
  await expect(page.locator('#launcher')).toBeHidden()
  await expect(page.locator('#sidebar')).toBeVisible()
  await expect(page.locator('#profile-message')).toBeVisible()
  await page.locator('#rerender').click()
  await expect(page.locator('#launcher')).toBeHidden()
  await page.locator('#insert').click()
  await expect(page.locator('#later-launcher')).toBeHidden()
  await page.locator('#master').click()
  await expect(page.locator('#launcher')).toBeVisible()
  await expect(page.locator('#later-launcher')).toBeVisible()
  await page.locator('#master').click()
  await expect(page.locator('#launcher')).toBeHidden()
  await page.locator('#child').click()
  await expect(page.locator('#launcher')).toBeVisible()
  await page.locator('#parent').click()
  await expect(page.locator('#sidebar')).toBeHidden()
  await expect(page.locator('#launcher')).toBeHidden()
  await page.locator('#rerender').click()
  await expect(page.locator('#launcher')).toBeHidden()
  await page.locator('#parent').click()
  await expect(page.locator('#sidebar')).toBeVisible()
  await expect(page.locator('#launcher')).toBeVisible()
})

test('floating detection releases a launcher moved into normal flow', async ({ page }) => {
  await page.goto('/tests/browser/floating-dms.html')
  await page.locator('#child').click()
  await expect(page.locator('#launcher')).toBeHidden()
  await page.locator('#move').click()
  await expect(page.locator('#launcher')).toBeVisible()
})
